"""
Aegis Data Models
Dataclasses for health records, emotions, check-ins, and proactive alerts.
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field, asdict
from datetime import datetime
from typing import Optional, List, Dict, Any


# ─── Emotion ─────────────────────────────────────────────────────────────────

@dataclass
class EmotionResult:
    """Result of emotion analysis from voice features."""
    label: str                          # calm / stressed / anxious / fatigued / neutral
    confidence: float                   # 0.0 – 1.0
    pitch_mean: float                   # Hz
    pitch_std: float                    # Hz
    energy_rms: float                   # RMS amplitude
    speech_rate: float                  # approx words per second
    secondary_label: Optional[str] = None      # secondary emotion for mixed emotions
    secondary_confidence: Optional[float] = None  # confidence of secondary emotion
    is_mixed: bool = False              # True if mixed emotion detected
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)
    
    def get_emotion_description(self) -> str:
        """Get human-readable emotion description."""
        if self.is_mixed and self.secondary_label:
            return f"{self.label} and {self.secondary_label}"
        return self.label


# ─── Health Check‑in ─────────────────────────────────────────────────────────

@dataclass
class HealthCheckIn:
    """A single daily health check-in record."""
    id: str = field(default_factory=lambda: uuid.uuid4().hex[:12])
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())
    mood_score: Optional[float] = None          # 1–10
    sleep_hours: Optional[float] = None
    energy_level: Optional[float] = None        # 1–10
    pain_notes: Optional[str] = None
    medication_taken: Optional[bool] = None
    user_text: Optional[str] = None             # raw transcription
    detected_emotion: Optional[str] = None      # from voice analysis
    emotion_confidence: Optional[float] = None
    notes: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)
    
    def to_json(self) -> str:
        """
        Serialize HealthCheckIn to JSON string.
        
        Returns:
            JSON string representation of the HealthCheckIn object
        """
        import json
        return json.dumps(self.to_dict(), ensure_ascii=False)
    
    @classmethod
    def from_json(cls, json_str: str) -> 'HealthCheckIn':
        """
        Parse HealthCheckIn from JSON string.
        
        Args:
            json_str: JSON string representation of a HealthCheckIn object
        
        Returns:
            HealthCheckIn object parsed from JSON
        
        Raises:
            ValueError: If JSON is invalid or missing required fields
        """
        import json
        data = json.loads(json_str)
        return cls(**data)


# ─── Medication Reminder ─────────────────────────────────────────────────────

@dataclass
class MedicationReminder:
    """A medication reminder entry."""
    id: str = field(default_factory=lambda: uuid.uuid4().hex[:12])
    name: str = ""
    dosage: str = ""
    schedule_time: str = ""        # e.g., "08:00", "20:00"
    active: bool = True
    created_at: str = field(default_factory=lambda: datetime.now().isoformat())

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


# ─── Vital Signs (optional wearable data) ────────────────────────────────────

@dataclass
class VitalRecord:
    """A point-in-time vital sign reading."""
    id: str = field(default_factory=lambda: uuid.uuid4().hex[:12])
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())
    heart_rate: Optional[int] = None            # bpm
    blood_pressure_sys: Optional[int] = None
    blood_pressure_dia: Optional[int] = None
    spo2: Optional[float] = None                # %
    temperature: Optional[float] = None         # °C
    steps: Optional[int] = None

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


# ─── Proactive Alert ─────────────────────────────────────────────────────────

@dataclass
class ProactiveAlert:
    """An alert generated by the proactive engine."""
    id: str = field(default_factory=lambda: uuid.uuid4().hex[:12])
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())
    alert_type: str = ""                # "low_mood", "sleep_deficit", "medication_missed", etc.
    severity: str = "info"              # "info", "warning", "urgent"
    message: str = ""
    explanation: str = ""               # Why this alert was generated (Requirement 10.10)
    acknowledged: bool = False
    context: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


# ─── Conversation Turn ──────────────────────────────────────────────────────

@dataclass
class ConversationTurn:
    """A single turn in a conversation (user or assistant)."""
    role: str                           # "user" or "assistant"
    content: str
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())
    emotion: Optional[str] = None
    tone_mode: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


# ─── Session ─────────────────────────────────────────────────────────────────

@dataclass
class Session:
    """A conversation session with Aegis."""
    id: str = field(default_factory=lambda: uuid.uuid4().hex[:12])
    started_at: str = field(default_factory=lambda: datetime.now().isoformat())
    turns: List[ConversationTurn] = field(default_factory=list)
    emotion_history: List[EmotionResult] = field(default_factory=list)
    active: bool = True

    def add_turn(self, role: str, content: str, emotion: Optional[str] = None,
                 tone_mode: Optional[str] = None):
        self.turns.append(ConversationTurn(
            role=role, content=content, emotion=emotion, tone_mode=tone_mode
        ))

    def get_context_window(self, max_turns: int = 10) -> List[Dict]:
        """Return recent turns for LLM context."""
        recent = self.turns[-max_turns:]
        return [t.to_dict() for t in recent]
    
    def add_emotion(self, emotion: EmotionResult):
        """Add an emotion result to the history."""
        self.emotion_history.append(emotion)
    
    def detect_emotion_transition(self) -> Optional[Dict[str, Any]]:
        """
        Detect emotion transitions between the last two turns.
        
        Returns a dictionary with transition information if a transition occurred,
        or None if no transition detected.
        
        A transition is detected when:
        - There are at least 2 emotions in history
        - The emotion labels differ between the last two turns
        
        Returns:
            Dictionary with:
            - from_emotion: previous emotion label
            - to_emotion: current emotion label
            - from_confidence: previous emotion confidence
            - to_confidence: current emotion confidence
            - timestamp: timestamp of the transition
            - transition_type: descriptive type (e.g., "calm_to_stressed")
        """
        if len(self.emotion_history) < 2:
            return None
        
        previous = self.emotion_history[-2]
        current = self.emotion_history[-1]
        
        # Check if emotion changed
        if previous.label == current.label:
            return None
        
        return {
            "from_emotion": previous.label,
            "to_emotion": current.label,
            "from_confidence": previous.confidence,
            "to_confidence": current.confidence,
            "timestamp": current.timestamp,
            "transition_type": f"{previous.label}_to_{current.label}"
        }
